# generated by datamodel-codegen:
#   filename:  quality-control-description-json-schema.json
#   timestamp: 2025-01-21T07:01:55+00:00

# This file is generated from the json schemas in:
# https://github.com/statisticsnorway/arkitektur-informasjonsmodeller/tree/main/process-data
# Generated by the pydantic tool datamodel-code-generator and the command:
# poetry run datamodel-codegen --input quality-control-description-json-schema.json --input-file-type jsonschema --output quality_control_data.py
# And then added some minor modifications

from enum import Enum

from pydantic import BaseModel
from pydantic import Field


class QualityControlType(Enum):
    H = "H"
    S = "S"
    I = "I"  # noqa:E741


class Variable(BaseModel):
    variable_description: str | None = None


class QualityControlData(BaseModel):
    quality_control_id: str = Field(..., description="A unique quality control ID")
    quality_control_description: str = Field(
        ..., description="Quality control description"
    )
    quality_control_type: QualityControlType = Field(
        ..., description="Quality control type: hard (M), soft (S), informative (I)"
    )
    variables: list[Variable] = Field(
        ...,
        description="A description of which variables must be included in the quality control.",
    )
